
#https://docs.getdbt.com/reference/dbt_project.yml

name: L2C_Analytics

config-version: 2
version: 1.0.0

profile: L2C_Analytics

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
docs-paths: ["documentations"]

packages-install-path: "dbt_packages"

clean-targets:
  - "target"
  - "dbt_packages"

query-comment: "executed by dbt"

flags:
  partial_parse: true

 
  require_generic_test_arguments_property: true
quoting:
  database: false
  schema: false
  identifier: false

# models:
#   L2C_Analytics:
#     +persist_docs:
#       relation: true
#       columns: true

#     bronze:
#       +tags: ["bronze"]
#       +schema: bronze
#       +materialized: view
      
#     silver:
#       +tags: ["silver"]
#       +schema: silver
#       +materialized: table

#     gold:
#       +tags: ["gold"]
#       +schema: gold
#       +materialized: table


